services:
  api:
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop: [ "ALL" ]
    read_only: true

  worker:
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop: [ "ALL" ]
    read_only: true

  ui:
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop: [ "ALL" ]
    read_only: true

  react:
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop: [ "ALL" ]
    read_only: true

  redis:
    restart: unless-stopped

  db:
    restart: unless-stopped

  minio:
    restart: unless-stopped

  createbuckets:
    restart: "no"
