apiVersion: apps/v1
kind: Deployment
metadata:
  name: srw-worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels: { app: srw-worker }
  template:
    metadata:
      labels: { app: srw-worker }
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["celery","-A","api.workers.celery_app:celery_app","worker","--loglevel=INFO"]
          envFrom:
            - configMapRef:
                name: srw-env
          resources: {{- toYaml .Values.worker.resources | nindent 12 }}
